Update lang-pairs path and add fixed-dictionary for small models
With missing file extension in --lang-pairs option generation fails with the following error
ValueError: language pair en-fr contains languages that are not in the language dictionary; langs: ['language_pairs_small_models']

However generation still fails after restoring file extension with following error:
RuntimeError: Error(s) in loading state_dict for TransformerModel:
	size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([128112, 1024]) from checkpoint, the shape in current model is torch.Size([128104, 1024]).
	size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([128112, 1024]) from checkpoint, the shape in current model is torch.Size([128104, 1024]).
	size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([128112, 1024]) from checkpoint, the shape in current model is torch.Size([128104, 1024]).
This could be resolved by adding --fixed-dictionary model_dict.128k.txt like in Generation for the 12B model section.