Update torch.full to include device kwarg
Summary:
Follow-up to D21718233. Turns out that the `type_as` call which was previously replaced was also changing the device (which is undocumented).

We are now getting failures in the PyText regression tests due to this, e.g. f194917776:
```
File "/mnt/xarfuse/uid-195423/2d6064ba-seed-9eb81dc4-e043-40e2-b455-d693dd405cff-ns-4026534163/fairseq/modules/fb_elmo_token_embedder.py", line 262,
 in _with_sentence_boundaries
    input = torch.cat([bos_block, input, pad_block], dim=1)
RuntimeError: All input tensors must be on the same device. Received cuda:0 and cpu

```

Reviewed By: mruberry

Differential Revision: D21893042

fbshipit-source-id: dacef19d76780f50c0d443a511515c019a24cfdd