Add default dataclass to space_tokenizer and nltk_tokenizer
Summary:
The default dataclass of `space_tokenizer` is `None`, this somehow breaks when we load a model with space tokenizer from `torch.hub` (full message: P154020599):

```
...
hydra.errors.MissingConfigException: Could not load tokenizer/space.
Available options:
        moses
```

Adding default dataclass to `FairseqDataclass` to solve the problem.

Note: another fix might be setting the default dataclass to `FairseqDataclass` here:
https://www.internalfb.com/intern/diffusion/FBS/browsefile/master/fbcode/deeplearning/projects/fairseq-py/fairseq/registry.py?commit=1ae2e67d969ca090b41a6fa33ca9aaf360a26d3f&lines=63

Reviewed By: myleott

Differential Revision: D25466594

fbshipit-source-id: aa4ec23731081e266ce641ea3db179169233842c