Fix a crash in Early Stopping when --validate-interval is greater than 1
Summary:
When --validate-interval is set to greater than 1, the validation loss is set to None for those epochs where no validation was done.

This caused a crash in Early Stopping if the "--patience" option was set to a positive value. The reason is that `valid_loss` is compared with `prev_best`, resulting a crash when None is compared to a float:
```
TypeError: '>' not supported between instances of 'NoneType' and 'float'
```

A simple check is added to the should_stop_early() method which skips checking if no validation is done in the current epoch.

Reviewed By: myleott

Differential Revision: D20318486

fbshipit-source-id: 3a1bc4894f7e21dc196f552b0d0b857b8fb5cb7f